#!/usr/bin/env python3
"""A smoke test that runs the real app, not a mock of it.

The unit tests cover the arithmetic and the decisions. Nothing covered the
window, and the failures this codebase actually hits all live there: a command
registered without its permission file, a capability line left out, and panels
that are not the width their labels claim. Each one passes `cargo test` and
then breaks everything.

Run it with the app already open:

    python3 scripts/smoke-test.py

Or have it start the built app first:

    python3 scripts/smoke-test.py --start

It needs a screen, so it is a local check rather than something for CI.
Exits non-zero on the first real failure, and says what it expected.
"""

import argparse
import json
import os
import pathlib
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG = (
    pathlib.Path.home()
    / "Library/Application Support/com.digitaldecibels.breakpoints/breakpoints.json"
)
BRIDGE = "http://127.0.0.1:7333"
APP_CANDIDATES = [
    pathlib.Path.home() / "Applications/BreakPoints.app",
    pathlib.Path("/Applications/BreakPoints.app"),
    ROOT / "src-tauri/target/release/bundle/macos/BreakPoints.app",
]

passed = 0
failures = []


def check(name, ok, detail=""):
    global passed
    if ok:
        passed += 1
        print(f"  ok    {name}")
    else:
        failures.append((name, detail))
        print(f"  FAIL  {name}")
        if detail:
            print(f"        {detail}")
    return ok


def token():
    if not CONFIG.is_file():
        sys.exit(f"no config at {CONFIG}: run the app once first")
    return json.loads(CONFIG.read_text())["bridgeToken"]


def call(tool, body=None, timeout=60):
    request = urllib.request.Request(
        f"{BRIDGE}/api/{tool}",
        data=json.dumps(body or {}).encode(),
        headers={
            "Authorization": f"Bearer {token()}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return json.loads(response.read())
    except urllib.error.HTTPError as err:
        # A refused tool call is a 400 carrying `{"error": ...}`, which is the
        # answer rather than a transport failure.
        body = err.read()
        try:
            return json.loads(body)
        except json.JSONDecodeError:
            return {"error": f"HTTP {err.code}", "body": body.decode(errors="replace")}


def bridge_is_up():
    try:
        urllib.request.urlopen(f"{BRIDGE}/health", timeout=2)
        return True
    except Exception:
        return False


# ---- the checks that need no window ---------------------------------------


def check_commands_are_registered():
    """Every command needs a permission file and a capability line.

    Neither is generated. Missing the first fails the build script with a
    message that names every other command; missing the second fails only that
    one command, at runtime, silently.
    """
    lib = (ROOT / "src-tauri/src/lib.rs").read_text()
    block = re.search(r"generate_handler!\[(.*?)\]", lib, re.S).group(1)
    commands = [c.strip().split("::")[-1] for c in block.split(",") if c.strip()]

    missing_files = [
        c
        for c in commands
        if not (ROOT / f"src-tauri/permissions/autogenerated/{c}.toml").is_file()
    ]
    check(
        "every command has a permission file",
        not missing_files,
        f"missing: {missing_files}",
    )

    granted = json.loads((ROOT / "src-tauri/capabilities/default.json").read_text())[
        "permissions"
    ]
    missing_grants = [
        c for c in commands if f"allow-{c.replace('_', '-')}" not in granted
    ]
    check(
        "every command is granted in the capability",
        not missing_grants,
        f"missing: {missing_grants}",
    )


def check_tools_match_their_definitions():
    """A tool in the dispatch but not the definitions is invisible to an agent;
    one in the definitions but not the dispatch is advertised and then errors."""
    bridge = (ROOT / "src-tauri/src/bridge.rs").read_text()
    names = re.search(r"pub const TOOL_NAMES: &\[&str\] = &\[(.*?)\];", bridge, re.S)
    listed = set(re.findall(r'"([a-z_]+)"', names.group(1)))
    # Only the definitions block, or the server's own name in `initialize`
    # counts as a tool.
    definitions = bridge[bridge.index("fn tool_definitions"):]
    defined = set(re.findall(r'"name": "([a-z_]+)"', definitions))
    check(
        "every tool name has a definition",
        listed == defined,
        f"only in the list: {sorted(listed - defined)}; only defined: {sorted(defined - listed)}",
    )


# ---- the checks that need the window --------------------------------------


def check_the_bridge_answers():
    health = json.loads(
        urllib.request.urlopen(f"{BRIDGE}/health", timeout=5).read()
    )
    check("the bridge answers", health.get("name") == "breakpoints", str(health))
    return health


def check_auth_is_required():
    try:
        urllib.request.urlopen(
            urllib.request.Request(
                f"{BRIDGE}/api/list_panels", data=b"{}",
                headers={"Content-Type": "application/json"},
            ),
            timeout=5,
        )
        check("an unauthorised request is refused", False, "it was allowed")
    except urllib.error.HTTPError as err:
        check("an unauthorised request is refused", err.code == 401, f"got {err.code}")


def check_panels_are_the_width_they_claim():
    panels = call("list_panels")
    if not check("the row has panels", bool(panels), "no panels open"):
        return []

    silent = [p["name"] for p in panels if p.get("reportedWidth") is None]
    check(
        "every panel has reported its width",
        not silent,
        f"silent: {silent}. A panel that never reports has no scroll sync, no "
        f"console capture and no problem reports.",
    )

    wrong = [
        f"{p['name']} says {p.get('reportedWidth')} not {p['width']}"
        for p in panels
        if p.get("widthMismatch")
    ]
    check("every panel is the width on its label", not wrong, "; ".join(wrong))

    loaded = [p for p in panels if (p["state"].get("state") if isinstance(p["state"], dict) else p["state"]) == "loaded"]
    check(
        "every panel loaded",
        len(loaded) == len(panels),
        f"{len(panels) - len(loaded)} of {len(panels)} did not",
    )
    return panels


def check_a_panel_answers_questions(panels):
    if not panels:
        return
    name = panels[0]["name"]
    width = call("eval_js", {"panel": name, "script": "return window.innerWidth;"})
    check(
        "a panel answers an eval",
        width == panels[0]["width"],
        f"asked {name} for its width, got {width}, expected {panels[0]['width']}",
    )

    error = call("eval_js", {"panel": name, "script": "throw new Error('expected');"})
    check(
        "an error in a panel comes back as an error",
        isinstance(error, dict) and "expected" in str(error.get("error", "")),
        str(error),
    )


def check_bad_input_is_refused():
    cases = [
        ("a URL that will not parse", "navigate", {"url": "http:// not a url"}),
        ("an unknown panel", "eval_js", {"panel": "no-such-panel", "script": "return 1;"}),
        ("a missing argument", "eval_js", {"panel": "0"}),
    ]
    for label, tool, body in cases:
        result = call(tool, body)
        check(
            f"{label} is refused",
            isinstance(result, dict) and "error" in result,
            f"got {str(result)[:120]}",
        )


def check_the_report_queue_survives():
    """The queue is written to disk, so a restart must not lose it."""
    path = CONFIG.with_name("reports.json")
    if not path.is_file():
        check("the report queue file exists", True, "nothing waiting, which is fine")
        return
    try:
        saved = json.loads(path.read_text())
        check(
            "the report queue parses",
            isinstance(saved.get("reports", []), list),
            str(saved)[:120],
        )
    except json.JSONDecodeError as err:
        check("the report queue parses", False, str(err))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--start", action="store_true", help="open the built app first if it is not running"
    )
    args = parser.parse_args()

    print("Break/Points smoke test")
    print("\nsource checks")
    check_commands_are_registered()
    check_tools_match_their_definitions()

    if not bridge_is_up() and args.start:
        app = next((a for a in APP_CANDIDATES if a.exists()), None)
        if not app:
            sys.exit("no built app found: run `npm run tauri build` first")
        print(f"\nstarting {app}")
        # -g so it never takes focus from whatever is in front of it.
        subprocess.run(["open", "-g", "-a", str(app)], check=True)
        for _ in range(60):
            if bridge_is_up():
                break
            time.sleep(2)
        time.sleep(10)  # boot restores the project and opens the row

    if not bridge_is_up():
        sys.exit(
            "\nthe bridge is not answering on 7333. Open Break/Points, turn the agent "
            "bridge on in Settings, or run this with --start."
        )

    print("\nrunning app")
    check_the_bridge_answers()
    check_auth_is_required()
    panels = check_panels_are_the_width_they_claim()
    check_a_panel_answers_questions(panels)
    check_bad_input_is_refused()
    check_the_report_queue_survives()

    print(f"\n{passed} passed, {len(failures)} failed")
    for name, detail in failures:
        print(f"  {name}: {detail}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
